@isTest(seeAllData=false)
public class UCDA_ParserContainerAsyncRequestCtrlTest {
    public static testMethod void UCDA_ParserContainerAsyncRequestCtrlTestMethod(){
        	UCDA_ParserContainerAsyncRequestCtrl c = new UCDA_ParserContainerAsyncRequestCtrl();
        	c.id = 'sdfasd';
      		c.success = false;
    		c.errors = new List<UCDA_ParserContainerAsyncRequestCtrl.Errors>();
    		c.warnings = new List<UCDA_ParserContainerAsyncRequestCtrl.Errors>();
       }
}